# Generated by Django 5.0.2 on 2025-07-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternativa',
            options={'verbose_name': 'Alternativa', 'verbose_name_plural': 'Alternativas'},
        ),
        migrations.AlterModelOptions(
            name='pontuacao',
            options={'verbose_name': 'Pontuação', 'verbose_name_plural': 'Pontuações'},
        ),
        migrations.AddField(
            model_name='pergunta',
            name='resposta_correta_vf',
            field=models.BooleanField(blank=True, help_text='Para questões de Verdadeiro/Falso: True = Verdadeiro, False = Falso', null=True),
        ),
    ]
