# Generated by Django 5.0.2 on 2025-07-12 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_alternativa_options_alter_pontuacao_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='resposta_correta_vf',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='resposta_verdadeiro_falso',
            field=models.BooleanField(blank=True, help_text="Para questões Verdadeiro/Falso: marque se a resposta correta for 'Verdadeiro'", null=True),
        ),
    ]
